name: CI_with_coderrect

on: [push, pull_request]

jobs:

  coderrect-ubuntu-latest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: build
      # Fail build if there are warnings
      # build with TLS just for compilation coverage
      run: make REDIS_CFLAGS='-Werror' BUILD_TLS=yes

    - name: Coderrect Scan
      uses: coderrect-inc/coderrect-github-action@v1.2
      with:
        cleanCommand: "make distclean"
        buildCommand: "make REDIS_CFLAGS='-Werror' BUILD_TLS=yes"
        options: "-analyzeBinaries=redis-server,redis-cli"
    
    
